### ISSUE TITLE
安卓MCU登录认证失

### ISSUE THREAD

**Issue by hunantangyuyang** [xuwei9/BVCU-SDK-Demo#1]
我下载了贵司提供的BVCUSDK并登录成功，现在我copy登录部分的代码进行登录，可还是返回 -65522 ，下面是打印的log：2020-02-23 14:49:15.794 20396-20396/com.hntyy.myapplication I/CoreSDK: ----------------->PostMessageToNative LOGIN2020-02-23 14:49:15.794 20396-20396/com.hntyy.myapplication I/CoreSDK: ----------------->S_ID -> LOGIN2020-02-23 14:49:15.794 20396-20396/com.hntyy.myapplication I/CoreSDK: ----------------->I_RESULT -> 12020-02-23 14:49:15.794 20396-20396/com.hntyy.myapplication I/CoreSDK: <-----------------PostMessageToNative2020-02-23 14:49:15.794 20396-20396/com.hntyy.myapplication I/CoreSDK: 2020-02-23_14:49:15.794725 <FAIL> RefObject [0xffc508c4] destroyed with count=22020-02-23 14:49:15.794 20396-20396/com.hntyy.myapplication I/tyy: loginStatus:-65522
--
AuthEventCallback------iAuthResult=1024,authKeyStatus=16,iCertType=65537,iToken=48974,szSerialNumber=term_571a85b8463d95c235e26638fff73430,iAuthAvailableKeyCount=-1
如上log所示，authResult是1024，认证也成功的。请问是什么原因，还需要做些什么

**Comment by jinbo1996** [comment]
-65522应该是BVCU.getSDK().login(param);方法直接的返回值吧，请重新检查每个登录参数。可与bvcu_demo的登录参数一一比较，请注意登录参数中szClientID变量的值

**Comment by hunantangyuyang** [comment]
> -65522应该是BVCU.getSDK().login(param);方法直接的返回值吧，请重新检查每个登录参数。可与bvcu_demo的登录参数一一比较，请注意登录参数中szClientID变量的值

loginStatus:-65522   ip=120.79.85.243   port=9701  username=admin  password=888888  serverParam.szClientID=UA_47725
loginStatus:1   ip=120.79.85.243   port=9701  username=admin  password=888888  serverParam.szClientID=UA_42689
这是我打印出来的login方法的参数及serverParam.szClientID

**Comment by jinbo1996** [comment]
可否将你的demo发我看看

**Comment by hunantangyuyang** [comment]
> 可否将你的demo发我看看

可以，请问我怎么发给你。 我直接QQ或者微信发给你？

**Comment by jinbo1996** [comment]
直接发这里就可以了，将工程打包拖到输入框

**Comment by jinbo1996** [comment]
是在收到认证成功的回调后再登录的吗，主要前后顺序，先认证，认证成功再登录

**Comment by hunantangyuyang** [comment]
我是直接跟着doAuth()方法执行login()的，执行login()方法的时候，回调还没执行所以登录不成功。我把登录函数放在回调里执行就成功了。原来是这样，谢谢

**Comment by jinbo1996** [comment]
好的
