### ISSUE TITLE
请教关于SDK的对讲及GPS定位信息的问题。

### ISSUE THREAD

**Issue by hunantangyuyang** [xuwei9/BVCU-SDK-Demo#2]
1.对讲功能我没有看到，请问SDK的对讲功能在哪？
2.获取到设备列表后，json数据pPUList中的设备的经度和纬度都为0，或者经度为0。

**Comment by xuwei9** [comment]
好，我们后面在demo中添加对讲功能和获取GPS信息的功能，完成后，会更新到github上，及时关注更新

**Comment by hunantangyuyang** [comment]
> 好，我们后面在demo中添加对讲功能和获取GPS信息的功能，完成后，会更新到github上，及时关注更新

好的，麻烦尽快完善。非常感谢

**Comment by xuwei9** [comment]
对讲和获取GPS信息功能已更新到最新地址https://github.com/besovideo/Android-BVCU-SDK-Demo，本地址将不再更新

**Comment by xuwei9** [comment]
本地址将不再更新
